name: pp71
description: "MendDate app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  theme_provider: ^0.6.0
  google_fonts: ^6.1.0
  get_it: ^7.6.7
  flutter_launcher_icons: ^0.13.1
 
  
  path_provider: ^2.1.2
  webview_flutter_android: ^3.14.0
  webview_flutter_wkwebview: ^3.10.2
  webview_flutter: ^4.4.4
  flutter_gen: ^5.4.0
  flutter_markdown: ^0.6.18+3
  flutter_svg: ^2.0.9
  in_app_review: ^2.0.8
  flutter_app_info: ^2.0.0
  flutter_native_splash:
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.5
  flutter_bloc: ^8.1.4
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  firebase_core: ^2.25.3
  firebase_remote_config: ^4.3.12
  firebase_crashlytics: ^3.4.13 
  hive: ^2.2.3
  hive_generator: ^2.0.1
  percent_indicator: ^4.2.3
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  linear_progress_bar: ^1.1.1
  calendar_date_picker2: ^0.5.5
  table_calendar: ^3.0.9

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher.png"
  min_sdk_android: 21 


dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/launcher.png

flutter_gen:
  output: lib/core/generated/
  line_length: 80
  integrations:
    flutter_svg: true
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

